# Generated by Django 4.1 on 2022-08-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
