# Generated by Django 4.1 on 2022-11-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name_plural': 'Product Gallery'},
        ),
        migrations.RenameField(
            model_name='productgallery',
            old_name='images',
            new_name='image',
        ),
    ]
