# Generated by Django 4.1 on 2022-09-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_variation_options'),
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderedproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
